name: Deploy App
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: 'Use Node.js 18'
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: 'Install dependencies'
      working-directory: ./db-sync-chat-app
      run: 'pnpm install --frozen-lockfile'
    - name: 'Test'
      working-directory: ./db-sync-chat-app
      run: 'pnpm test'

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: test
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      CLOUDSDK_COMPUTE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: true
        workload_identity_provider: 'projects/507296512815/locations/global/workloadIdentityPools/ci-cd-pool/providers/github'
        service_account: 'uptick-service-account@eazy-run-2022.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: farayolaj/uptick-chat-app-db-sync
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./db-sync-chat-app
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: 'Copy compose.yaml and nginx.conf to server'
      run: 'gcloud compute scp db-sync-chat-app/compose.yaml db-sync-chat-app/nginx.conf uptick-chat-app:~/'
    - name: 'Run docker compose up'
      run: 'gcloud compute ssh uptick-chat-app -- docker compose up --remove-orphans -d'
